---
title: "Tidy Data"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Pivot longer

```{r}

# Import data
pulse_df = 
  read_sas("Data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()

pulse_df

# Pivot longer
pulse_tidy = 
  pulse_df %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    # Get rid of bdi_score_ bit before the value for visit variable
    names_prefix = "bdi_score_",
    values_to = "bdi_score"
  ) %>% 
  mutate(
    # In this variable, look for every instance where variable == bl, and everywhere that condition is true, replace with 00m
    visit = replace(visit, visit == "bl", "00m"),
    # Often easier to think of categoricals as factors, rather than character variables
    visit = factor(visit)
  )

pulse_tidy
```

## Pivot wider

Make up a results data table

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("a", "b", "a", "b"),
    group_mean = c(4, 8, 3, 6)
  )
analysis_df

## Pivot wider

analysis_df %>% 
  pivot_wider(
    names_from = "time",
    values_from = "group_mean"
  ) %>% 
  # Use format more human readable once knit
  knitr::kable()
```

## Binding rows

Import the LOTR movie words stuff

```{r}
# Load LOTR data
fellowship_df = 
  read_excel("Data/LotR_Words.xlsx",
             range = "B3:D6"
  ) %>% 
  mutate(movie = "fellowship_rings")
fellowship_df

two_towers_df = 
  read_excel("Data/LotR_Words.xlsx",
             range = "F3:H6"
  ) %>% 
  mutate(movie = "two_towers")
two_towers_df

return_king_df = 
  read_excel("Data/LotR_Words.xlsx",
             range = "J3:L6"
  ) %>% 
  mutate(movie = "return_kind")
return_king_df

# Bind rows into one df, then pivot longer
lotr_df = 
  # Use bind_rows over rbind; it is better
  bind_rows(fellowship_df, two_towers_df, return_king_df) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>% 
  # Put movie as first variable
  relocate(movie)
lotr_df
```

## Joins

Look at FAS data

```{r}
litters_df =
  read_csv("Data/FAS_litters.csv")
```
